apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
  containers:
    - name: web
      image: dlarin/web:1.1
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-container
      image: busybox:1.31.0
      command: [ 'sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh' ]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
